### ISSUE TITLE
Portal delay is inconsistent

### ISSUE THREAD

**Issue by qixils** [Stabyourself/mari0#21]
The delay between portal shots fluctuates between 12 & 13 frames due to rounding errors. Reducing the delay from 0.2s to 0.19s would probably:tm: fix this. (Or just try to fix the rounding errors.)

**Comment by Noahkiq** [comment]
![image](https://user-images.githubusercontent.com/13265322/45394244-b7cfc380-b5fd-11e8-949c-fcb16ec009d0.png)

**Comment by Masterjun3** [comment]
This issue is part of a bigger rounding issue of every timer.

Due to the double-precision floating-point format of numbers in Lua, given a perfect situation with 60 FPS, the actual `dt` values given by LÖVE would fluctuate between
`~0.0166666666666666664353702032031 (hex 0x3F91111111111111)`
and
`~0.0166666666666666699048171551567 (hex 0x3F91111111111112)`
Our goal is to never have a too small `dt` value (to avoid not processing things we should have processed), so adding a small number fixes the problem.

As [Wikipedia](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) states:
> The spacing as a fraction of the numbers in the range from 2<sup>n</sup> to 2<sup>n+1</sup> is 2<sup>n−52</sup>

This means from 32 FPS to 64 FPS, the error is at most 2<sup>-58</sup> (~3.46944695e-18, as you can see above), so to make sure we never use too small numbers, adding 1e-16 to `dt` should suffice.

<hr>

https://github.com/Stabyourself/mari0/blob/7a971fc793690ddb19e684d2c3f7fa617eedf6ed/main.lua#L751

Adding `dt = dt + 1e-16` **before** this line should fix all rounding errors.

<hr>

<sup>As a side effect, this means the game will process slightly higher values, which will have a noticeable effect of around a single frame per day if you play at a million FPS (or a frame per several millennia if you play at normal speeds)</sup>

**Comment by Stabyourself** [comment]
I don't like the idea of changing dt or changing delays to be very slightly different.
I'm open for other ideas though.

**Comment by Masterjun3** [comment]
Even though I suggested the idea, changing `dt` does sound like a bad solution. If changing the delays is not an option, then the only other thing I can suggest is using floating point comparison methods like they are usually done, by checking if the value lies inside an error margin (example [here](https://floating-point-gui.de/errors/comparison/)).
